### ISSUE TITLE
paper entries should store DOI, wherever available

### ISSUE THREAD

**Issue by ltalirz** [danieleongari/CURATED-COFs#1]
URLs to journal articles may change, while publishers promise to keep DOIs resolving to the right place.

**Comment by danieleongari** [comment]
I agree, 
we plan, in the latest `additions` to turn the URL column into DOI, or to use in all the cases `http://doi.org/{DOI}` as URL.

**Comment by danieleongari** [comment]
done https://github.com/danieleongari/CURATED-COFs/commit/ec169eb117b4dc65addede1876b6e7643ed5e285
