### ISSUE TITLE
Duplicates policy: make a label but refer to another CIF

### ISSUE THREAD

**Issue by danieleongari** [danieleongari/CURATED-COFs#18]
In the case of `p1609` (https://onlinelibrary.wiley.com/doi/full/10.1002/anie.201606155) there is a COF which is is not included: TpBD.
However, this is already present in the database with two entries flagged as duplicates:
* 13150N2, named also TpBD
* 16320N2, named TpFn

We can consider, for these cases, to make anyway an entry `16091N2` but without CIF, and just refer to 13150N2. This policy can be extended also to 16320N2 and `TpFn` can be inserted as `name_alternative` extra in the AiiDA database. 

### Pro:
* the user that look at that paper knows that the COF is in the database
* we avoid to add it, and then realize that there is a duplicate
* this policy can be extended to other duplicates
### Cons:
* there is no 1:1 correspondence between lines in the csv and CIF files

**Comment by ltalirz** [comment]
Not sure whether you already chose a solution for this now.

My view:
 * I definitely agree it's good to record the fact that a COF mentioned in the paper is present in the database
 * Not duplicating CIF files also sounds reasonable; no strong opinion on this
 
i.e. feel free to go ahead

**Comment by danieleongari** [comment]
Duplicated CIFs that are recognized after submission, are moved to the `cof-deprecated` list (https://github.com/danieleongari/CURATED-COFs/pull/22)
