### ISSUE TITLE
Output of some sanity checks

### ISSUE THREAD

**Issue by kjappelbaum** [danieleongari/CURATED-COFs#19]
Hi, for a project with @AndresOrtegaGuerrero I ran some sanity checks on the current master branch. Most of them might be fine after the optimization. There are some more flagged but I need to check them more carefully.

- `20116N3`: overvalent c / I wouldn't expect a multicenter H bond (probably fixed after optimization)
- `20010N2`: strange chemistry (probably fixed after optimization)
- `17080C2`: Br-H distances / multicenter H bond (probably fixed after optimization)
- `20440N3`: Cl-H distances / multicenter H bond (probably fixed after optimization)
- `19141N2`: There is no H at all

**Comment by ltalirz** [comment]
Thanks for reporting!

there are a couple of known issues listed here in the tracker - the plan is to fix all of them together in the January update

**Comment by ltalirz** [comment]
@danieleongari have these been incorporated?

**Comment by danieleongari** [comment]
* 20116N3: fixed after opt
* 20010N2: fixed after opt
* 17080C2: all charged frameworks still need appropriate curation
* 20440N3: fixed after opt
* 19141N2: discarded as AB
