### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by ltalirz** [danieleongari/CURATED-COFs#2]
add a license in order to let people know how they can reuse this data

**Comment by danieleongari** [comment]
I will consider adding the MIT licence.

**Comment by danieleongari** [comment]
Since also https://github.com/core-cof/CoRE-COF-Database/tree/2c1419d1f3c0d6eccce4306728cfe151c6b2ee08, from which this work is nested, does not provide a licence, I can not impose a permissive licence to this project.

**Comment by danieleongari** [comment]
Since a MIT license was added to https://github.com/core-cof/CoRE-COF-Database/blob/master/LICENSE,
I added the same.
See: 3d8633da300fd56960a8e3fb7b437dc04fa8ecae
