### ISSUE TITLE
Error importing update from Oct. 20

### ISSUE THREAD

**Issue by Surluson** [danieleongari/CURATED-COFs#20]
I've been getting the following error when trying to import the updated dataset from Oct. 20th (file gotten from here)

![image](https://user-images.githubusercontent.com/21219867/98455893-5814ca80-212b-11eb-9f1a-9a38d4d74d41.png)

Anyone have any idea what the problem could be?
I didn't have this issue when importing the version from Sep 9.

**Comment by ltalirz** [comment]
Hey @Surluson thanks for the report - would you mind trying to update your aiida version to the latest `develop` branch and try again?

We needed a new feature to export metadata on the AiiDA group level, which was supposed to be in 1.5.0 but the release has been delayed by a few days.

Let me know if that fixes the issue - if not, I'll look into it

**Comment by Surluson** [comment]
Hi @ltalirz , thanks for the help!
I used the following command to pip install `aiida-core` from the `develop` branch:

`pip install "git+https://github.com/aiidateam/aiida-core.git@develop"`

But it still installed version `1.4.3` and I seem to be getting the same error (unsurprisingly). It seems the `develop` branch is still at v.1.4.3 (see https://github.com/aiidateam/aiida-core/blob/develop/aiida/__init__.py) unless I'm misunderstanding something.

If you have any input how to properly update to v.1.5.0 I would love it, if not feel free to close the Issue

Cheers,
-Arni

**Comment by ltalirz** [comment]
Thanks for checking.

> But it still installed version `1.4.3`

This is expected - at the moment, the version number is bumped only for the new release.
I agree that this is not ideal and have [opened an issue for it](https://github.com/aiidateam/aiida-core/issues/4551).

> I seem to be getting the same error (unsurprisingly).

That is more surprising to me. I now tested the import on `develop` (ac4c881ad12cca669d4b7b1745d6dd5f0553a1ba) and it worked fine for me:

```
$ verdi -p cofs-2020-10-28 import export_discovery_cof_28Oct20.aiida
\
IMPORT
--------  ----------------------------------
Archive   export_discovery_cof_28Oct20.aiida

Parameters
--------------------------  ------
Comment rules               newest
New Node Extras rules       import
Existing Node Extras rules  kcl

Summary
-----------------------  ---------------
Auto-import Group label  20201109-014350
User(s)                  1 new
Computer(s)              9 new
Node(s)                  584029 new
Group(s)                 625 new
Log(s)                   238938 new
Link(s)                  1568158 new

Success: imported archive export_discovery_cof_28Oct20.aiida
```

I suggest you try two things:

 * open a python shell and do `import aiida; aiida.__file__` to see whether you are picking up the aiida package that you're expecting
 * try importing this 10-material subset that I've just created for testing purposes (should be much faster) https://www.dropbox.com/s/a4m1fhlchvtltrb/subset.aiida?dl=0

**Comment by Surluson** [comment]
Thanks again @ltalirz 
I tried the subset and it worked.
I then tried the the whole dataset and it worked!

I must've updated the package wrong or something, sorry for my dumbness :laughing:
