### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by ltalirz** [danieleongari/CURATED-COFs#23]
so far we've only tagged the original release (v1.0.0)

We should also tag the versions corresponding to the periodic updates published on the Materials Cloud archive [link](https://archive.materialscloud.org/record/2020.133)

**Comment by ltalirz** [comment]
Since the releases are periodic, I suggest calendar versioning, i.e.
 * v19.12
 * v20.02
 * v20.06
 * v20.09
 * v20.10
 * v21.02

**Comment by danieleongari** [comment]
I think the version naming you suggested is perfect

**Comment by ltalirz** [comment]
tags have been created https://github.com/danieleongari/CURATED-COFs/releases

the latest one will be added after merging the feb updated
