### ISSUE TITLE
DOI/Title for p1629

### ISSUE THREAD

**Issue by dwsideriusNIST** [danieleongari/CURATED-COFs#28]
My students discovered a DOI mismatch for paper p1629

`p1629,"Science, 2016, 351, 361-365",10.1126/science.aad0832,Active sites of nitrogen-doped carbon materials for oxygen reduction reaction clarified using model catalysts`

should be associated with COF 16290N3, "COF-505" but that paper is about catalysts.

The correct reference should be:

`p1629,"Science, 2016, 351, 365-369",10.1126/science.aad4011,Weaving of organic threads into a crystalline covalent organic framework`

I made a change to cof-papers.csv with the correction, but then the commit failed the pre-commit tests - I'd be doing a PR otherwise. Unfortunately, I do not have time to track down the issue today!

**Comment by ltalirz** [comment]
Thanks, Dan! Feel free to make a PR with a failing pre-commit - we can take care of fixing it.

**Comment by danieleongari** [comment]
Fixed in https://github.com/danieleongari/CURATED-COFs/pull/29, thanks!
