### ISSUE TITLE
Overview of toplogies

### ISSUE THREAD

**Issue by SanderBorgmans** [danieleongari/CURATED-COFs#30]
Hi,

Is there some way to consult the topology of each structure (e.g. hcb or dia)?

Thanks!

**Comment by danieleongari** [comment]
Thanks for asking, 
@kjappelbaum is this some analysis that [mofchecker](https://github.com/kjappelbaum/mofchecker) can do, for this scope?

We would not add the topology directly in the metadata, but possibly suggest a robust algorithm to compute it from the CIF: indeed there may be some fine-tuning needed to achieve an effective mapping of the topologies.

**Comment by kjappelbaum** [comment]
>@kjappelbaum is this some analysis that mofchecker can do, for this scope?

it is on the long-term feature wish list for another project but it will require some thought as the clustering algorithm i currently have for MOFs needs to be adjusted to also deal with MOFs (a key step currently depends on starting a BFS from the metal)
