### ISSUE TITLE
Article citation mismatch for 16160N2

### ISSUE THREAD

**Issue by dwsideriusNIST** [danieleongari/CURATED-COFs#34]
The citation record for COF 16160N2 has a mismatch.

Article p1616 has:
ID p1616
Citation: Adv. Energy Mater., 2016, 6, 1601189
DOI: 10.1039/C7CC05172G
Title: Facile synthesis of sponge-like Ni 3 N/NC for electrocatalytic water oxidation

The title matches the DOI, but not the citation. If I backtrack the citation, I think the correct paper is https://doi.org/10.1002/aenm.201601189. I do not have a subscription to Adv Energy Mater to confirm; but the IISERP-COF3 material is mentioned in the Supplementary Materials.

I've submitted PR #33

**Comment by ltalirz** [comment]
Hi @mpougin , are you planning to keep this repository up to date for a while?
If yes, can I suggest to click the button to watch the repo so that you will be notified of issues being opened?

If not, we should think whether we can find another maintainer

**Comment by mpougin** [comment]
Hello,
Thanks for the heads-up @ltalirz. Yes, I will maintain this repository and track issues from now on

**Comment by mpougin** [comment]
Thank you @dwsideriusNIST, I checked your suggestions and you're right. I merged your PR and will close the issue now
