### ISSUE TITLE
Possible duplicate in the database (16083N2.cif, 16523N2.cif)

### ISSUE THREAD

**Issue by kjappelbaum** [danieleongari/CURATED-COFs#8]
Hi, 

I just tested the `find_duplicates` function in the `structure_comp` package that we've started developing during my master's thesis. 
 
I ran it with default settings, i.e. first looking for composition duplicates for the Niggli cells (fast) for  which then the structure graphs are compared (pretty slow, also attempting supercells if there seems to be one. If you would want to use it directly in a webapp the graphs would need to be precalculated and we anyway discussed with Leo that this might be nice to have as `extra`). I used the `cif` from the default branch (last commit 9613654). Will later push the notebook to the `structure_comp` examples. 

I didn't analyze more carefully, but`16083N2.cif` and `16523N2.cif` look quite similar to me.

Cheers,
Kevin

**Comment by danieleongari** [comment]
Thanks, I will flag them as duplicates. 
You can also add the most recent branch in your analysis, I'm going to merge it soon (this week).

**Comment by kjappelbaum** [comment]
Seems it did not find any additional duplicates.

**Comment by danieleongari** [comment]
Great, thanks!

**Comment by danieleongari** [comment]
This comes from an entry that because of an error in the DOI was completely duplicated (4 materials out of 4).

**Comment by danieleongari** [comment]
Solved https://github.com/danieleongari/CURATED-COFs/pull/7

**Comment by kjappelbaum** [comment]
Thanks for reporting that there are more duplicates. Indeed there were more duplicates found in the first search step.
For some reason I overlooked '16082N2.cif', '16522N2.cif' which was also found by `structure_comp`. But since I we then still overlooked two duplicates, I closer looked in the code and found that there is a bug in `structure_comp`. If we manually construct the graph they are indeed equal also for the other two but when we compress the output of all the comparisons we somehow loose this. I'll check also again on the full database once I did the fix, sorry for that.

**Comment by kjappelbaum** [comment]
<img width="327" alt="Screen Shot 2020-06-24 at 13 36 41" src="https://user-images.githubusercontent.com/32935233/85548981-cd21b080-b61f-11ea-9bfe-09633dc13b82.png">

So, the issue seems to be that the remaining pair that we were not able to find with `structure_comp` was of different composition. 

 H192 C296 N40 (`16081N2.cif`) vs. H192 C292 N40 (`16521N3.cif`)

**Comment by danieleongari** [comment]
Yes, that's ok: it was missing a carbon atom!

**Comment by kjappelbaum** [comment]
Sorry for bothering you (and thanks for helping me spotting the bug). I reran and found the following pairs

```
[('13051N2.cif', '12000N2.cif'),
 ('19455N2.cif', '19454N2.cif'),
 ('13150N2.cif', '16320N2.cif'),
 ('20163N2.cif', '20164N2.cif')]
```

Again, I did no inspection beyond looking at them in VESTA and they indeed seems similar.

**Comment by ltalirz** [comment]
@danieleongari Can you please check these structures?

I've also just opened #9 that will catch duplicate DOIs in the future.
Happy to add more simple checks if there are any (could even directly use kevin's algorithms if they are fast enough)

Does it make sense to fix this before making the June update?

**Comment by kjappelbaum** [comment]
> could even directly use kevin's algorithms if they are fast enough

If the graphs are stored as extra it should be quite efficient (and anyhow I implemented a `cached` version somewhen, which used cached graphs, and we try to use efficient datastructures like KDTrees). Do not have time today, but will check on the weekend as I'll go back to CSD/CoRE

**Comment by danieleongari** [comment]
Reagarding the duplicates you found,
>[('13051N2.cif', '12000N2.cif'),
 ('19455N2.cif', '19454N2.cif'),
 ('13150N2.cif', '16320N2.cif'),
 ('20163N2.cif', '20164N2.cif')]

the first and third are already mentioned as `duplicates` in `cof-frameworks.csv` while the other two are probably a manual error of submitting twice the same framework instead of the new one. This can happen if the CIF structure does not load in the submission form, but you don't notice it: we need to prevent this happening in the submission form. 
Since it is a minor problem will fix it at the next CURATED-COFs update.

**Comment by ltalirz** [comment]
@danieleongari is this fixed now?

**Comment by danieleongari** [comment]
Fixed in https://github.com/danieleongari/CURATED-COFs/pull/22
